spring.application.name=f1-jms-system
spring.artemis.mode=embedded
spring.artemis.embedded.persistent=false
spring.artemis.embedded.queues=MECHANICS_ALERT.QUEUE,DRIVER_ALERT.QUEUE,PIT_STOP_REQUEST.QUEUE
spring.artemis.embedded.topics=TELEMETRY.TOPIC
spring.jms.template.receive-timeout=5000
logging.level.edu.pja.sri.f1system=DEBUG
logging.level.org.springframework.jms=INFO
logging.level.org.apache.activemq.audit.base=WARN
logging.level.org.apache.activemq.audit.message=WARN
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%15.15thread] %-40.40logger{39} : %msg%n
